name: Run Tech API tests

on:
  push:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Berlin"
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group test_api
      - name: Add virtualenv to PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: true
          job-summary: true
          custom-arguments: "tests/tests_api --cov-report=term-missing --cov=custom_components.tech.tech tests/"
          click-to-expand: true
          report-title: "Tech API test report"
